main: map.cpp playeractions.cpp shipplacement.cpp robotactions.cpp expertMode.cpp Starting_screen.cpp modes.cpp main.cpp
	g++ -pedantic-errors -std=c++11 map.cpp playeractions.cpp shipplacement.cpp robotactions.cpp Starting_screen.cpp modes.cpp expertMode.cpp main.cpp -o main -l ncurses

clean:
	rm -f main
